### ISSUE TITLE
How to use dialogs extension with "telegram-bot-sdk dev-master branch"

### ISSUE THREAD

**Issue by thomasgroch** [zarincheg/telegram-bot-dialogs#1]
I wonder if it would be possible to use this extension with the dev-master branch of [telegram-bot-sdk](https://github.com/irazasyed/telegram-bot-sdk).

I tried to run:
`composer require zarincheg / telegram-bot-dialogs dev-master`

And I got this response:
`[InvalidArgumentException]
  Could not find package zarincheg at any version for your minimum-stability (stable). Check the package spelling or your minimum-sta
  bility`

How could I "force" composer authorize the installation of this dependence?

**Comment by zarincheg** [comment]
Hi! I am didn't test the extension with the latest version of telegram-bot-sdk yet. I plan to make it soon and I will make necessary changes, if needed.
But I think you can try to downgrade minimum-stability requirement in your composer.json file to "dev"

**Comment by zarincheg** [comment]
For now it is better to set `"zarincheg/telegram-bot-dialogs": ">=0.2@dev"` in composer.json
