### ISSUE TITLE
Standalone Feature

### ISSUE THREAD

**Issue by brytey2k** [zarincheg/telegram-bot-dialogs#16]
Does this library work stand alone like https://github.com/irazasyed/telegram-bot-sdk

**Comment by zarincheg** [comment]
@brytey2k This library requires https://github.com/irazasyed/telegram-bot-sdk and predis. But you can use it without Laravel. Or what exactly do you mean?

**Comment by brytey2k** [comment]
Ok.. great... Thanks for the response
