### ISSUE TITLE
Is this repository no longer maintained?

### ISSUE THREAD

**Issue by lptn** [zarincheg/telegram-bot-dialogs#24]
hey @zarincheg 
It seems like this repository is not maintained anymore. If you don't have any plans to maintain it, how about archiving it and updating README.md to redirect visitors to this fork: https://github.com/koot-labs/telegram-bot-dialogs ? Thank you!

**Comment by zarincheg** [comment]
Hi, it was so long time ago :) I'll make a review of all forks and yours, and add the links for sure.

**Comment by zarincheg** [comment]
@lptn done
